### ISSUE TITLE
Fonttools build error: load_designspace: assert base_idx is None

### ISSUE THREAD

**Issue by eliheuer** [lettersoup/Sofia-Sans#8]
```
Traceback (most recent call last):
...
  File "/Users/Air/Py/emode/fonttools/Lib/fontTools/varLib/__init__.py", line 819, in build
    ds = load_designspace(designspace)
  File "/Users/Air/Py/emode/fonttools/Lib/fontTools/varLib/__init__.py", line 751, in load_designspace
    assert base_idx is None
AssertionError
```

Fonttools isn't finding a base master:
```python
	# Find base master
	base_idx = None
	for i,m in enumerate(normalized_master_locs):
		if all(v == 0 for v in m.values()):
			assert base_idx is None
			base_idx = i
	assert base_idx is not None, "Base master not found; no master at default location?"
	log.info("Index of base master: %s", base_idx)

	return _DesignSpaceData(
		axes,
		internal_axis_supports,
		base_idx,
		normalized_master_locs,
		masters,
		instances,
		ds.rules,
	)

**Comment by eliheuer** [comment]
Adding a `Variable Font Origin` custom parameter does nothing and far as I can tell. I tried adding one for each axis.

**Comment by eliheuer** [comment]
This is fixed in an incoming PR
